services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=zappai
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    volumes:
      - ./docker_volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432       
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
