services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=zappai
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zappai -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ZAPPAI_DB_HOST=postgres
      - ZAPPAI_DB_PORT=5432
      - ZAPPAI_DB_USER=zappai
      - ZAPPAI_DB_PASSWORD=1234
      - ZAPPAI_DB_NAME=db
    volumes:
      - backend_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
      
volumes:
  postgres_data:
  backend_logs:
