"""Initial

Revision ID: 1302fd041417
Revises: 
Create Date: 2024-05-27 16:27:36.304266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1302fd041417'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_climate_data',
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('u_component_of_wind_10m', sa.Float(), nullable=False),
    sa.Column('v_component_of_wind_10m', sa.Float(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('evaporation', sa.Float(), nullable=False),
    sa.Column('total_precipitation', sa.Float(), nullable=False),
    sa.Column('surface_pressure', sa.Float(), nullable=False),
    sa.Column('surface_solar_radiation_downwards', sa.Float(), nullable=False),
    sa.Column('surface_thermal_radiation_downwards', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('longitude', 'latitude', 'year', 'month')
    )
    op.create_table('past_climate_data',
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('u_component_of_wind_10m', sa.Float(), nullable=False),
    sa.Column('v_component_of_wind_10m', sa.Float(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('evaporation', sa.Float(), nullable=False),
    sa.Column('total_precipitation', sa.Float(), nullable=False),
    sa.Column('surface_pressure', sa.Float(), nullable=False),
    sa.Column('surface_solar_radiation_downwards', sa.Float(), nullable=False),
    sa.Column('surface_thermal_radiation_downwards', sa.Float(), nullable=False),
    sa.Column('surface_net_solar_radiation', sa.Float(), nullable=False),
    sa.Column('surface_net_thermal_radiation', sa.Float(), nullable=False),
    sa.Column('precipitation_type', sa.Float(), nullable=False),
    sa.Column('snowfall', sa.Float(), nullable=False),
    sa.Column('total_cloud_cover', sa.Float(), nullable=False),
    sa.Column('dewpoint_temperature_2m', sa.Float(), nullable=False),
    sa.Column('soil_temperature_level_1', sa.Float(), nullable=False),
    sa.Column('volumetric_soil_water_layer_1', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('longitude', 'latitude', 'year', 'month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('past_climate_data')
    op.drop_table('future_climate_data')
    # ### end Alembic commands ###
