"""Initial tables

Revision ID: 5e69aabb6ebd
Revises: 
Create Date: 2024-05-24 15:44:56.627757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '5e69aabb6ebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_climate_data',
    sa.Column('coordinates_str', sa.String(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='month'), nullable=False),
    sa.Column('precipitations', sa.Float(), nullable=False),
    sa.Column('surface_temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('coordinates_str', 'year', 'month')
    )
    op.create_index('idx_future_climate_data_coordinates', 'future_climate_data', ['coordinates'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_future_climate_data_coordinates', table_name='future_climate_data', postgresql_using='gist')
    op.drop_table('future_climate_data')
    # ### end Alembic commands ###
