""" Initial message

Revision ID: a5998ec1caca
Revises: 
Create Date: 2024-05-24 17:26:27.613813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a5998ec1caca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('future_climate_data',
    sa.Column('coordinates_str', sa.String(), nullable=False),
    sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER', name='month'), nullable=False),
    sa.Column('u_component_of_wind_10m', sa.Float(), nullable=False),
    sa.Column('v_component_of_wind_10m', sa.Float(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('evaporation', sa.Float(), nullable=False),
    sa.Column('total_precipitation', sa.Float(), nullable=False),
    sa.Column('surface_pressure', sa.Float(), nullable=False),
    sa.Column('surface_solar_radiation_downwards', sa.Float(), nullable=False),
    sa.Column('surface_thermal_radiation_downwards', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('coordinates_str', 'year', 'month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('future_climate_data')
    # ### end Alembic commands ###
